UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Mikkelin kesäyliopiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Mikkelin kesäyliopiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Muhoksen kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Muhoksen kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Työväen Akatemian Kannatusosakeyhtiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Työväen Akatemian Kannatusosakeyhtiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Limingan Kansanopiston Kannattajayhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Limingan Kansanopiston Kannattajayhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Otsolan Kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Otsolan Kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Siikajoen kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Siikajoen kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Vaasan kesäyliopisto ry - Vasa Sommaruniversitet rf.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Vaasan kesäyliopisto ry - Vasa Sommaruniversitet rf.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Linnalan Setlementti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Linnalan Setlementti ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Pohjois-Savon kansanopistoseura ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Pohjois-Savon kansanopistoseura ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Länsi-Suomen opistoyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Länsi-Suomen opistoyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Mänttä-Vilppulan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Mänttä-Vilppulan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Österbottens Svenska Kristliga Folkhögskolesällskap rf.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Österbottens Svenska Kristliga Folkhögskolesällskap rf.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kaustisen Evankelisen Opiston Kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kaustisen Evankelisen Opiston Kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Juuan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Juuan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Itä-Karjalan Kansanopistoseura ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Itä-Karjalan Kansanopistoseura ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Joensuun kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Joensuun kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Porin kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Porin kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Muonion kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Muonion kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Jyväskylän kesäyliopistoyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Jyväskylän kesäyliopistoyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Hyrynsalmen kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Hyrynsalmen kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Oriveden kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Oriveden kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Seinäjoen kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Seinäjoen kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Ylivieskan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Ylivieskan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Paltamon kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Paltamon kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Stiffelsen för Hangö sommaruniversitet.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Stiffelsen för Hangö sommaruniversitet.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Raision kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Raision kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Mikkelin kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Mikkelin kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Rovaniemen kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Rovaniemen kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Vasa stad.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Vasa stad.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Ahlmanin koulun säätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Ahlmanin koulun säätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Mikkelin kaupunki, Otavan Opisto.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Mikkelin kaupunki, Otavan Opisto.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kouvolan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kouvolan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kiteen Evankelisen Kansanopiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kiteen Evankelisen Kansanopiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Portaanpää ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Portaanpää ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Säkylän kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Säkylän kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kauhajoen kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kauhajoen kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Ilmajoen kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Ilmajoen kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Rovaniemen koulutuskuntayhtymä.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Rovaniemen koulutuskuntayhtymä.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Vaalan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Vaalan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Sulkavan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Sulkavan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Inarin kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Inarin kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Laitilan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Laitilan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Keski-Uudenmaan koulutuskuntayhtymä.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Keski-Uudenmaan koulutuskuntayhtymä.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Sallan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Sallan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Puolangan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Puolangan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Fria kristliga folkhögskolföreningen rf.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Fria kristliga folkhögskolföreningen rf.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kemijärven kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kemijärven kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Perheniemen Evankelisen Opiston Kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Perheniemen Evankelisen Opiston Kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Keski-Pohjanmaan koulutusyhtymä.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Keski-Pohjanmaan koulutusyhtymä.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Alavuden kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Alavuden kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Porvoon kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Porvoon kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Parikkalan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Parikkalan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Ikaalisten kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Ikaalisten kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Päijät-Hämeen kesäyliopistoyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Päijät-Hämeen kesäyliopistoyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Karstulan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Karstulan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Suomen teologinen opisto ry, nimi muutettu 15.03.2016.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Suomen teologinen opisto ry, nimi muutettu 15.03.2016.PD"');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kokkolan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kokkolan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Harjulan Setlementti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Harjulan Setlementti ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kajaanin kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kajaanin kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Utsjoen kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Utsjoen kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Toimelan Setlementti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Toimelan Setlementti ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kolarin kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kolarin kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Koulutuskuntayhtymä Tavastia.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Koulutuskuntayhtymä Tavastia.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Helsingfors stad.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Helsingfors stad.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kristinestads stad.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kristinestads stad.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Espoon kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Espoon kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Karkkilan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Karkkilan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Savonlinnan kristillinen opisto ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Savonlinnan kristillinen opisto ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Imatran kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Imatran kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Lieksan kristillisen opiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Lieksan kristillisen opiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kirkkopalvelut ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kirkkopalvelut ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Mäntsälän kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Mäntsälän kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Raseborg-säätiö, Karjaa.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Raseborg-säätiö, Karjaa.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Pöytyän kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Pöytyän kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Mäntyharjun kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Mäntyharjun kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kauhajoen evankelisen opiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kauhajoen evankelisen opiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kuurojen Liitto ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kuurojen Liitto ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Valkeakosken kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Valkeakosken kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Lahden kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Lahden kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Ruoveden kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Ruoveden kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Helsingin seudun kesäyliopistosäätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Helsingin seudun kesäyliopistosäätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Puumalan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Puumalan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Laukaan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Laukaan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Iin kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Iin kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kanneljärven kansanopiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kanneljärven kansanopiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kvarnen Samkommun.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kvarnen Samkommun.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Jyväskylän kristillisen opiston säätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Jyväskylän kristillisen opiston säätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Jokelan kansalaisopiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Jokelan kansalaisopiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Reisjärven Kristillinen Kansanopistoyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Reisjärven Kristillinen Kansanopistoyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Merikarvian kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Merikarvian kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Lieksan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Lieksan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Etelä-Karjalan kansalaisopisto-säätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Etelä-Karjalan kansalaisopisto-säätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Garantiföreningen för Evangeliska folkhögskolan i Svenskfinland rf.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Garantiföreningen för Evangeliska folkhögskolan i Svenskfinland rf.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Limingan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Limingan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Palkansaajien koulutussäätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Palkansaajien koulutussäätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kittilän kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kittilän kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kansallinen Sivistysliitto ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kansallinen Sivistysliitto ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Karstulan Evankelisen Kansanopiston Kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Karstulan Evankelisen Kansanopiston Kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Tuusulan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Tuusulan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Korpisaaren Säätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Korpisaaren Säätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Forssan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Forssan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Folkhälsan Utbildning Ab.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Folkhälsan Utbildning Ab.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Oulun kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Oulun kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Pihtiputaan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Pihtiputaan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Hyvinkään kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Hyvinkään kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Sibbo kommun.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Sibbo kommun.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Nurmeksen kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Nurmeksen kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Helsingin Evankelisen Opiston Säätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Helsingin Evankelisen Opiston Säätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Iitin kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Iitin kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Valkealan krsitillisen kansaopiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Valkealan krsitillisen kansaopiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Helsingin kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Helsingin kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Tampereen kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Tampereen kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Vantaan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Vantaan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Varsinais-Suomen Aikuiskoulutussäätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Varsinais-Suomen Aikuiskoulutussäätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Pieksämäen kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Pieksämäen kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Pietarsaaren kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Pietarsaaren kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Auralan Setlementti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Auralan Setlementti ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Tohmajärven kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Tohmajärven kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Nurmijärven Opiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Nurmijärven Opiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Taivalkosken kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Taivalkosken kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Samkommunen för Västra Nylands folkhögskola.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Samkommunen för Västra Nylands folkhögskola.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Pedersöre kommun.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Pedersöre kommun.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Snellman-instituutti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Snellman-instituutti ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Sotkamon kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Sotkamon kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Setlementti Kyrkökoskela ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Setlementti Kyrkökoskela ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Helsingin kristillisen opiston säätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Helsingin kristillisen opiston säätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kirkkonummen kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kirkkonummen kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Etelä-Pohjanmaan korkeakouluyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Etelä-Pohjanmaan korkeakouluyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Muurlan Evankelisen Opiston Säätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Muurlan Evankelisen Opiston Säätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kempeleen kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kempeleen kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kauniaisten kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kauniaisten kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Peruskansan Sivistysliitto ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Peruskansan Sivistysliitto ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kiuruveden kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kiuruveden kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Peräpohjolan Kansanopiston Kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Peräpohjolan Kansanopiston Kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Lievestuoreen Setlementti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Lievestuoreen Setlementti ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Espoon seudun koulutuskuntayhtymä Omnia.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Espoon seudun koulutuskuntayhtymä Omnia.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Pohjois-Satakunnan kansanopiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Pohjois-Satakunnan kansanopiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Lopen kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Lopen kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Koskelan Setlementti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Koskelan Setlementti ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Jyvälän Setlementti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Jyvälän Setlementti ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Haapajärven kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Haapajärven kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Raseborgs stad.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Raseborgs stad.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Ranuan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Ranuan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Ilomantsin kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Ilomantsin kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kalajoen Kristillisen Opiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kalajoen Kristillisen Opiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Sivistysliitto Kansalaisfoorumi SKAF ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Sivistysliitto Kansalaisfoorumi SKAF ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kansan Sivistyön Liitto KSL ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kansan Sivistyön Liitto KSL ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kainuun Opisto Oy.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kainuun Opisto Oy.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kainuun Korkeakouluyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kainuun Korkeakouluyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Ruokolahden kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Ruokolahden kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Jämsän Kristillinen Kansanopistoyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Jämsän Kristillinen Kansanopistoyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Pudasjärven kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Pudasjärven kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Turun kristillisen opiston säätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Turun kristillisen opiston säätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kannuksen kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kannuksen kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Tornion kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Tornion kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Rautjärven kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Rautjärven kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Sastamalan koulutuskuntayhtymä.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Sastamalan koulutuskuntayhtymä.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"SFV Bildning (ent. Svenska folkskolans vänner rf).pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'SFV Bildning (ent. Svenska folkskolans vänner rf).PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kaarinan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kaarinan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Vörå kommun.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Vörå kommun.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kiteen kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kiteen kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Jokioisten kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Jokioisten kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Nokian kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Nokian kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Jämsän kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Jämsän kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Åbo stad. Registratorskontoret.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Åbo stad. Registratorskontoret.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Valamon luostari.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Valamon luostari.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Hausjärven kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Hausjärven kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Loimaan evankelisen kansanopiston säätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Loimaan evankelisen kansanopiston säätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Keski-Pohjanmaan Korkeakouluyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Keski-Pohjanmaan Korkeakouluyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Savitaipaleen kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Savitaipaleen kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kinnulan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kinnulan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kronoby kommun.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kronoby kommun.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Teollisuusliitto ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Teollisuusliitto ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Salon kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Salon kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Turun Aikuiskoulutussäätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Turun Aikuiskoulutussäätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Turun kaupunki. kasvatus- ja opetusvirasto.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Turun kaupunki. kasvatus- ja opetusvirasto.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Pohjois-Pohjanmaan kesäyliopistoseura ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Pohjois-Pohjanmaan kesäyliopistoseura ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Haapaveden Opiston Kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Haapaveden Opiston Kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Järvenpään kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Järvenpään kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Axxel Utbildning Ab.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Axxel Utbildning Ab.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Suomen Evankelisluterilainen Kansanlähetys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Suomen Evankelisluterilainen Kansanlähetys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Suomen Raamuttuopiston Säätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Suomen Raamuttuopiston Säätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Lovisa stad.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Lovisa stad.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Järvilakeuden kansalaisopiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Järvilakeuden kansalaisopiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Haminan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Haminan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Opintotoiminnan Keskusliitto ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Opintotoiminnan Keskusliitto ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Maaseudun Sivistysliitto ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Maaseudun Sivistysliitto ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Naantalin kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Naantalin kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Ylitornion kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Ylitornion kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kurikkalan Setlementti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kurikkalan Setlementti ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Siilijärven kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Siilijärven kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Alkio-opiston Kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Alkio-opiston Kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Raahen kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Raahen kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Vetelin kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Vetelin kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Malax kommun.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Malax kommun.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kaskisten kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kaskisten kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Joutsan kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Joutsan kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Jyränkölän Setlementti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Jyränkölän Setlementti ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Saarijärven kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Saarijärven kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Lahden kansanopiston säätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Lahden kansanopiston säätiö.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kimitoöns kommun.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kimitoöns kommun.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Hankasalmen kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Hankasalmen kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kokemäen kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kokemäen kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Setlementti Kainulan Kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Setlementti Kainulan Kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Eurajoen kristillisen opiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Eurajoen kristillisen opiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Loimaan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Loimaan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kotkan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kotkan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Vihreä Sivistysliitto y - Gröna Bildningsförbundet rf.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Vihreä Sivistysliitto y - Gröna Bildningsförbundet rf.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Hämeenkyrön kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Hämeenkyrön kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Korsholms kommun.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Korsholms kommun.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Suomussalmen kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Suomussalmen kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Posion kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Posion kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Päivölän Kansanopiston Kannattajayhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Päivölän Kansanopiston Kannattajayhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Pielaveden kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Pielaveden kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Vieremän kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Vieremän kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Pohjantähti-opiston kannatusyhditys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Pohjantähti-opiston kannatusyhditys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Joutsenon opiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Joutsenon opiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Loviisan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Loviisan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Someron kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Someron kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Iisalmen kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Iisalmen kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Raudaskylän Kristillinen Opisto ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Raudaskylän Kristillinen Opisto ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Alajärven kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Alajärven kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Tampereen kesäyliopistoyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Tampereen kesäyliopistoyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Lapinlahden kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Lapinlahden kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Sonkajärven kunta.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Sonkajärven kunta.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Savonlinnan kesäyliopistoyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Savonlinnan kesäyliopistoyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Karjalan Evankelinen seura ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Karjalan Evankelinen seura ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Haapaveden kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Haapaveden kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Työväen Sivistysliitto TSL ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Työväen Sivistysliitto TSL ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Lapuan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Lapuan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kalajoen kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kalajoen kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Toimihenkilöjärjestöjen Sivistysliitto TJS ry - Funktionärorganisationernas Bildningsförbund FOB rf.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Toimihenkilöjärjestöjen Sivistysliitto TJS ry - Funktionärorganisationernas Bildningsförbund FOB rf.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Ranuan kristillinen kansanopistoyhdistys.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Ranuan kristillinen kansanopistoyhdistys.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Erityiskansanopiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Erityiskansanopiston kannatusyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Keuruun kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Keuruun kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Borgå folkakademi Ab.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Borgå folkakademi Ab.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Hämeen liitto.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Hämeen liitto.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Paasikiviopistoyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Paasikiviopistoyhdistys ry.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Keravan kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Keravan kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Ingå kommun.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Ingå kommun.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Paimion kaupunki.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Paimion kaupunki.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kymenlaakson liitto.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kymenlaakson liitto.PDF');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Rovalan Setlementti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Rovalan Setlementti ry.PDF' and diaarinumero = '134/532/2012');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Rovalan Setlementti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Rovalan Setlementti ry.PDF' and diaarinumero = '13/532/2011');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Itä-Hämeen kansansivistystyön säätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Itä-Hämeen kansansivistystyön säätiö.PDF' and diaarinumero = '36/532/2011') ;
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Itä-Hämeen kansansivistystyön säätiö.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Itä-Hämeen kansansivistystyön säätiö.PDF' and diaarinumero = '101/532/2012');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Vuolle Setlementti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Vuolle Setlementti ry.PDF' and diaarinumero = '28/532/2016');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Vuolle Setlementti ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Vuolle Setlementti ry.PDF' and diaarinumero = '29/532/2016');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kuusamo-opiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kuusamo-opiston kannatusyhdistys ry.PDF' and diaarinumero = '25/532/2012');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kuusamo-opiston kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kuusamo-opiston kannatusyhdistys ry.PDF' and diaarinumero = '109/532/2011');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kymenlaakson Opiston Kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kymenlaakson Opiston Kannatusyhdistys ry.PDF' and diaarinumero = '50/532/2011');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Kymenlaakson Opiston Kannatusyhdistys ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Kymenlaakson Opiston Kannatusyhdistys ry.PDF' and diaarinumero = '55/532/2012');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Toimihenkilöjärjestöjen Opintoliitto ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Toimihenkilöjärjestöjen Opintoliitto ry.PDF'and diaarinumero = '1/532/2016');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Toimihenkilöjärjestöjen Opintoliitto ry.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Toimihenkilöjärjestöjen Opintoliitto ry.PDF' and diaarinumero = '16/532/2012');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Närpes stad.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Närpes stad.PDF' and diaarinumero = '10/532/2011');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Närpes stad.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Närpes stad.PDF'  and diaarinumero = '46/532/2012');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Pohjois-Karjalan koulutuskuntayhtymä.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Pohjois-Karjalan koulutuskuntayhtymä.PDF' and diaarinumero = '213/532/2012');
UPDATE lupa SET meta = jsonb_set(meta, '{liitetiedosto}', '"Pohjois-Karjalan koulutuskuntayhtymä.pdf"' ) WHERE id = (select id from lupa where meta ->> 'liitetiedosto' = 'Pohjois-Karjalan koulutuskuntayhtymä.PDF' and diaarinumero = '12/532/2011');
